# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\zcproject\PYQT-label\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ZC_Label(object):
    def setupUi(self, ZC_Label):
        ZC_Label.setObjectName("ZC_Label")
        ZC_Label.setEnabled(True)
        ZC_Label.resize(1400, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ZC_Label.sizePolicy().hasHeightForWidth())
        ZC_Label.setSizePolicy(sizePolicy)
        ZC_Label.setMinimumSize(QtCore.QSize(1400, 600))
        self.centralwidget = QtWidgets.QWidget(ZC_Label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainlayout = QtWidgets.QGridLayout()
        self.mainlayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.mainlayout.setContentsMargins(0, 0, -1, -1)
        self.mainlayout.setObjectName("mainlayout")
        self.image_window = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.image_window.sizePolicy().hasHeightForWidth())
        self.image_window.setSizePolicy(sizePolicy)
        self.image_window.setMinimumSize(QtCore.QSize(1280, 480))
        self.image_window.setBaseSize(QtCore.QSize(0, 0))
        self.image_window.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.image_window.setMouseTracking(True)
        self.image_window.setAutoFillBackground(True)
        self.image_window.setText("")
        self.image_window.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.image_window.setObjectName("image_window")
        self.mainlayout.addWidget(self.image_window, 0, 0, 1, 1)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.button_layout.setObjectName("button_layout")
        self.file_name = QtWidgets.QLabel(self.centralwidget)
        self.file_name.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.file_name.setFont(font)
        self.file_name.setText("")
        self.file_name.setObjectName("file_name")
        self.button_layout.addWidget(self.file_name)
        self.cursor_coord = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cursor_coord.setFont(font)
        self.cursor_coord.setMouseTracking(False)
        self.cursor_coord.setText("")
        self.cursor_coord.setObjectName("cursor_coord")
        self.button_layout.addWidget(self.cursor_coord)
        self.labeled_number = QtWidgets.QLabel(self.centralwidget)
        self.labeled_number.setEnabled(True)
        self.labeled_number.setMinimumSize(QtCore.QSize(0, 0))
        self.labeled_number.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labeled_number.setFont(font)
        self.labeled_number.setText("")
        self.labeled_number.setObjectName("labeled_number")
        self.button_layout.addWidget(self.labeled_number)
        self.mainlayout.addLayout(self.button_layout, 1, 0, 1, 2)
        self.buttons = QtWidgets.QVBoxLayout()
        self.buttons.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.buttons.setObjectName("buttons")
        self.Q_damuzhi = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Q_damuzhi.setFont(font)
        self.Q_damuzhi.setStyleSheet("background-color: rgb(163, 0, 0);\n"
"color: white;")
        self.Q_damuzhi.setObjectName("Q_damuzhi")
        self.buttons.addWidget(self.Q_damuzhi)
        self.W_shizhi = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.W_shizhi.setFont(font)
        self.W_shizhi.setStyleSheet("background-color: rgb(0, 163, 0);\n"
"color: white;")
        self.W_shizhi.setObjectName("W_shizhi")
        self.buttons.addWidget(self.W_shizhi)
        self.E_bbox = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.E_bbox.setFont(font)
        self.E_bbox.setStyleSheet("background-color: rgb(163, 163, 0);")
        self.E_bbox.setObjectName("E_bbox")
        self.buttons.addWidget(self.E_bbox)
        self.A_prev = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.A_prev.setFont(font)
        self.A_prev.setObjectName("A_prev")
        self.buttons.addWidget(self.A_prev)
        self.D_next = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.D_next.setFont(font)
        self.D_next.setObjectName("D_next")
        self.buttons.addWidget(self.D_next)
        self.ESC_shut = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ESC_shut.setFont(font)
        self.ESC_shut.setObjectName("ESC_shut")
        self.buttons.addWidget(self.ESC_shut)
        self.mainlayout.addLayout(self.buttons, 0, 1, 1, 1)
        self.mainlayout.setColumnStretch(0, 3)
        self.mainlayout.setRowStretch(0, 3)
        self.horizontalLayout_2.addLayout(self.mainlayout)
        ZC_Label.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ZC_Label)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        ZC_Label.setMenuBar(self.menubar)
        self.actionopen_pic = QtWidgets.QAction(ZC_Label)
        self.actionopen_pic.setObjectName("actionopen_pic")
        self.actionopen_folder = QtWidgets.QAction(ZC_Label)
        self.actionopen_folder.setObjectName("actionopen_folder")
        self.menu_open_folder = QtWidgets.QAction(ZC_Label)
        self.menu_open_folder.setObjectName("menu_open_folder")
        self.menu.addAction(self.menu_open_folder)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ZC_Label)
        self.ESC_shut.clicked.connect(ZC_Label.close)
        QtCore.QMetaObject.connectSlotsByName(ZC_Label)

    def retranslateUi(self, ZC_Label):
        _translate = QtCore.QCoreApplication.translate
        ZC_Label.setWindowTitle(_translate("ZC_Label", "ZC label PyQt5"))
        self.Q_damuzhi.setText(_translate("ZC_Label", "大拇指(Q)"))
        self.Q_damuzhi.setShortcut(_translate("ZC_Label", "Q"))
        self.W_shizhi.setText(_translate("ZC_Label", "食指(W)"))
        self.W_shizhi.setShortcut(_translate("ZC_Label", "W"))
        self.E_bbox.setText(_translate("ZC_Label", "BBOX(E)"))
        self.E_bbox.setShortcut(_translate("ZC_Label", "E"))
        self.A_prev.setText(_translate("ZC_Label", "上一张(A)"))
        self.A_prev.setShortcut(_translate("ZC_Label", "A"))
        self.D_next.setText(_translate("ZC_Label", "下一张(D)"))
        self.D_next.setShortcut(_translate("ZC_Label", "D"))
        self.ESC_shut.setText(_translate("ZC_Label", "关闭(ESC)"))
        self.ESC_shut.setShortcut(_translate("ZC_Label", "Esc"))
        self.menu.setTitle(_translate("ZC_Label", "开始"))
        self.actionopen_pic.setText(_translate("ZC_Label", "打开图片"))
        self.actionopen_folder.setText(_translate("ZC_Label", "打开文件夹"))
        self.menu_open_folder.setText(_translate("ZC_Label", "打开文件夹"))

